const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

function assertNoUiEmoji(source, label) {
  for (const token of ["📊", "🔒", "📈", "🛠️", "📅", "🚀", "⚠️", "✅", "❌", "🔧", "💾", "📤", "📥", "🔍", "👁️", "🙈"]) {
    assert.equal(source.includes(token), false, `${label} should not contain ${token}`);
  }
}

test("automation page keeps only real local tool controls", () => {
  const html = fs.readFileSync(path.join(__dirname, "index.html"), "utf8");
  const app = fs.readFileSync(path.join(__dirname, "app.js"), "utf8");
  const api = fs.readFileSync(path.join(__dirname, "api.js"), "utf8");

  assert.match(html, /竞品监控 Web 控制台/);
  assert.match(html, /本周价格完整度/);
  assert.match(html, /id="btn-stop-task"/);
  assert.match(html, /请求停止/);
  assert.match(html, /发送当前模板/);
  assert.match(html, /id="template-upload-input"/);
  assert.match(html, /id="btn-upload-template"/);
  assert.match(html, /id="btn-download-template"/);
  assert.match(html, /运行日志/);
  assert.match(html, /结果记录/);
  assert.match(html, /企业微信/);
  assert.match(html, /id="cfg-run-date"/);
  assert.match(html, /id="cfg-dry-run"/);
  assert.match(html, /id="cfg-test-one"/);
  assert.match(html, /id="cfg-weekly-new-time"/);
  assert.match(html, /id="cfg-price-trend-time"/);
  assert.match(html, /目标 sheet 会按运行日期自动计算/);
  assert.match(html, /id="running-banner"/);
  assert.match(html, /id="running-banner-step"/);
  assert.match(html, /id="running-banner-progress-bar"/);
  assert.match(html, /id="workbook-sync-banner"/);
  assert.match(html, /id="btn-sync-template-main"/);
  assert.match(html, /role="status"/);
  assert.match(html, /id="daily-running-note"/);
  assert.match(html, /id="weekly-running-note"/);
  assert.match(html, /class="task-running-note"/);
  assert.match(app, /running-banner/);
  assert.match(app, /后台任务正在运行/);
  assert.match(app, /UIState\.isLiveStatus/);
  assert.match(app, /UIState\.activeTaskId/);
  assert.match(app, /task-card-running/);
  assert.match(app, /setTaskCardRunning\("daily-task-card", "daily-running-note"/);
  assert.doesNotMatch(html, /class="card-overlay"/);
  assert.doesNotMatch(app, /daily-overlay|weekly-overlay/);
  assert.match(html, /id="cfg-taobao-login-status"/);
  assert.match(html, /id="cfg-bi-login-status"/);
  assert.match(html, /class="today-workbench/);
  assert.match(html, /class="workbench-primary/);
  assert.match(html, /class="workbench-summary-grid/);
  assert.match(html, /id="console-result-preview"/);
  assert.match(html, /id="today-task-chip"/);
  assert.match(html, /id="btn-run-daily"/);
  assert.match(html, /id="btn-run-weekly"/);
  assert.match(app, /function handleTaskPrimary\(mode\)/);
  assert.match(app, /btn-run-daily"\)\.addEventListener\("click",\s*\(\)\s*=>\s*handleTaskPrimary\("daily_price"\)\)/);
  assert.match(app, /btn-run-weekly"\)\.addEventListener\("click",\s*\(\)\s*=>\s*handleTaskPrimary\("weekly_new"\)\)/);
  assert.doesNotMatch(app, /btn-run-daily"\)\.addEventListener\("click",\s*\(\)\s*=>\s*runTask\("daily_price"\)\)/);
  assert.match(html, /class="[^"]*\bidentity-section\b[^"]*"/);
  assert.match(html, /class="template-summary-card"/);
  assert.match(html, /class="template-main-row"/);
  assert.match(html, /class="template-meta-list"/);
  assert.match(html, /class="compact-upload-row"/);
  assert.match(html, /class="account-grid"/);
  assert.match(html, /class="account-card taobao-account-card"/);
  assert.match(html, /class="account-card bi-account-card"/);
  assert.match(html, /class="status-list"/);
  assert.match(html, /class="status-row"/);
  assert.match(html, /class="danger-note"/);
  assert.match(html, /class="btn danger-subtle"/);
  assert.match(html, /id="btn-save-config"/);
  assert.match(html, /id="btn-save-identity-config"/);
  assert.match(html, /保存账号与配置/);
  assert.match(html, /class="[^"]*\bconfig-save-state\b[^"]*"/);
  assert.match(html, /id="config-save-state"/);
  assert.match(html, /填写账号或密码后，请点击“保存账号与配置”/);
  assert.match(html, /保存后密码不会明文显示/);
  assert.match(html, /id="template-upload-input"/);
  assert.match(html, /id="btn-download-template-config"/);
  assert.match(html, /id="template-sync-status"/);
  assert.match(html, /id="template-primary-path"/);
  assert.match(html, /id="template-active-path"/);
  assert.match(html, /id="template-last-sync-at"/);
  assert.match(html, /id="template-last-sync-error"/);
  assert.match(html, /id="template-run-workbook-count"/);
  assert.match(html, /id="template-pending-sync-hint"/);
  assert.match(html, /id="btn-sync-template"/);
  assert.match(html, /id="btn-reset-taobao"/);
  assert.match(html, /id="btn-reset-bi"/);
  assert.match(html, /id="btn-clear-results"/);
  assert.match(html, /清空结果记录/);

  assert.doesNotMatch(html, /已释放 Session/);
  assert.doesNotMatch(html, /bg-glow-pink|bg-glow-blue/);
  assert.doesNotMatch(html, /\u7cfb\u7edf\u5065\u5eb7\u76d1\u63a7\u4e2d/);
  assert.doesNotMatch(html, /id="kpi-backup-count"/);
  assert.doesNotMatch(html, /\u672c\u5730\u6587\u4ef6\u72b6\u6001/);
  assert.doesNotMatch(html, />not_sent</);
  assertNoUiEmoji(html, "index.html");
  assertNoUiEmoji(app, "app.js");
  assert.doesNotMatch(html, /style="display:\s*flex;\s*align-items:\s*flex-start;\s*gap:\s*12px;"/);
  assert.doesNotMatch(html, /background:\s*linear-gradient\(135deg/);
  assert.doesNotMatch(app, /data:application\/vnd\.openxmlformats-officedocument\.spreadsheetml\.sheet/);
  assert.doesNotMatch(app, /UEsDBBQAAAAIA/);
  assert.match(app, /state\.logs\.slice\(0,\s*3\)/);
  assert.doesNotMatch(app, /state\.logs\.slice\(0,\s*5\)/);
  assert.match(app, /clearedLogKeys:\s*new Set\(\)/);
  assert.match(app, /logKey\(item\)/);
  assert.doesNotMatch(app, /API\.cleanupMaintenance\("logs"\)/);
  assert.match(app, /async function resetSession\(target\)[\s\S]*confirm\(/);
  assert.doesNotMatch(app, /🙈|👁️/);
  assert.match(app, /btn-download-template"\)\.addEventListener\("click",\s*\(\)\s*=>\s*downloadTemplate\("btn-download-template"\)\)/);
  assert.match(app, /btn-download-template-config"\)\.addEventListener\("click",\s*\(\)\s*=>\s*downloadTemplate\("btn-download-template-config"\)\)/);
  assert.match(app, /btn-sync-template"\)\.addEventListener\("click",\s*\(\)\s*=>\s*syncTemplate\("btn-sync-template"\)\)/);
  assert.match(app, /btn-sync-template-main"\)\.addEventListener\("click",\s*\(\)\s*=>\s*syncTemplate\("btn-sync-template-main"\)\)/);
  assert.match(app, /async function syncTemplate\(buttonId = "btn-sync-template"\)/);
  assert.match(app, /API\.syncTemplate\(\)/);
  assert.match(app, /workbook_sync_status/);
  assert.match(app, /async function downloadTemplate\(buttonId = "btn-download-template"\)/);
  assert.match(app, /async function exportResults\(\)[\s\S]*withButtonLoading\("btn-export-results"/);
  assert.match(app, /btn-clear-results"\)\.addEventListener\("click",\s*cleanupResults\)/);
  assert.match(app, /async function cleanupResults\(\)[\s\S]*API\.cleanupMaintenance\("results"\)/);
  assert.match(app, /不会删除 Excel、日志或备份文件/);
  assert.match(app, /async function backfillMissingDates\(\)[\s\S]*confirm\(/);
  assert.match(app, /handleLoopPrimaryAction\(\)[\s\S]*sendTemplate\("btn-loop-primary"\)/);
  assert.match(app, /async function sendTemplate\(buttonId = "btn-send-template-main"\)/);
  assert.match(app, /renderConsoleResults\(\)/);
  assert.match(app, /btn-save-identity-config/);
  assert.match(app, /weekly_new_time/);
  assert.match(app, /price_trend_time/);
  assert.match(app, /event\.submitter/);
  assert.match(app, /配置已保存，计划任务正在后台同步/);
  assert.match(app, /function setConfigDirty\(dirty\)/);
  assert.match(app, /beforeunload/);
  assert.match(app, /有未保存修改/);
  assert.match(api, /\/api\/template\/download/);
  assert.match(api, /\/api\/template\/upload/);
  assert.match(api, /\/api\/template\/sync-latest/);
  assert.match(api, /scope === "results"[\s\S]*CompetitorMonitorMock\.results = \[\]/);
  assert.doesNotMatch(html, /营销|会员|权限管理|数据大屏/);
});
